#!/usr/bin/env python3
"""
Static pages for search engines, generated from data/rdr2.db.

The app is one page that builds everything in the browser from a SQLite
file, behind a `#` in the address -- which a search engine reads as one
empty page.  This writes a plain HTML page for every material and every
recipe, at an address of its own, carrying the same facts the app's
cards do, so "perfect beaver pelt rdr2" has somewhere to land:

    materials/<slug>/index.html     one per ingredient
    recipes/<slug>/index.html       one per recipe
    materials/index.html            every material, A-Z, by kind
    recipes/index.html              every recipe, A-Z, by vendor
    sitemap.xml

Each page links on into the app, to the same card (#/materials/<id>),
for everything the app does that a page cannot: what you have, what you
still need, crafting.  The slug is the id without its prefix
(ing-perfect-beaver-pelt -> perfect-beaver-pelt), so an address stays
put when a name is corrected, and sw.js can turn one back into its id.

No JavaScript runs on these pages beyond the theme line every page
starts with, and every link in them is relative, so they work wherever
the site is served.  The one absolute address is SITE_URL, for the
canonical links and the sitemap.

Like rdr2.db, the output is generated and committed: run this after
every rebuild of the database.

    python3 scripts/build_pages.py            # write the pages
    python3 scripts/build_pages.py --check    # exit 1 if they are stale
"""

import argparse
import html
import json
import re
import shutil
import sqlite3
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = 'https://arindam-bose.github.io/adamslab/rdr2-crafting-guide/'
SITE_NAME = 'RDR2 Crafting Guide'

# Written into every generated page, and looked for before anything is
# deleted: a folder under materials/ or recipes/ without it was not
# made here, and is left alone.
MARKER = '<!-- generated by scripts/build_pages.py from data/rdr2.db; do not edit -->'

PREFIX = {'materials': 'ing-', 'recipes': 'recipe-'}

# The app's own words for each, from render.js and views/materials.js.
KIND_LABEL = {
    'animal': 'Animal material', 'plant': 'Plant', 'ammo': 'Ammo & throwables',
    'alcohol': 'Liquor', 'misc': 'Misc. item',
}
GROUPS = [
    ('Animal materials', ('animal',)),
    ('Plants', ('plant',)),
    ('Supplies', ('ammo', 'alcohol', 'misc')),
]
STATION_ICON = {
    'station-pearson': 'pearson', 'station-trapper': 'trapper',
    'station-fence': 'fence', 'station-campfire': 'campfire',
}
STATION_ORDER = ['station-pearson', 'station-trapper', 'station-fence', 'station-campfire']

# A station as the object of a sentence: Pearson is a man, the Trapper
# and the Fence are what people call them.
STATION_PROSE = {
    'station-pearson': 'Pearson', 'station-trapper': 'the Trapper',
    'station-fence': 'the Fence', 'station-campfire': 'your campfire',
}


# ------------------------------------------------------------
# small helpers, mirroring render.js
# ------------------------------------------------------------

def esc(value):
    return html.escape('' if value is None else str(value), quote=True)


def slug(id_, kind):
    return id_[len(PREFIX[kind]):]


def money(cents):
    return f'${cents / 100:.2f}'


def plural(n, word):
    return f'{n} {word}{"" if n == 1 else "s"}'


def listing(items):
    """'a', 'a and b', 'a, b and c'."""
    items = list(items)
    if len(items) < 2:
        return ''.join(items)
    return ', '.join(items[:-1]) + ' and ' + items[-1]


def icon(name):
    return f'<span class="icon icon-{name}" aria-hidden="true"></span>' if name else ''


def stars(quality):
    if not quality:
        return ''
    q = esc(quality)
    return (f'<span class="stars stars-{q.lower()}" role="img" '
            f'aria-label="{q}" title="{q}"></span>')


def quality_label(quality):
    if not quality:
        return ''
    return f'<span class="stars stars-{esc(quality.lower())}" aria-hidden="true"></span>{esc(quality)}'


def web_link(url, text):
    """Only a web address becomes a link, as in render.js."""
    if not re.match(r'^https?://', url or '', re.I):
        return esc(text)
    return (f'<a class="xlink" href="{esc(url)}" target="_blank" rel="noopener noreferrer" '
            f'title="{esc(text)} on the Red Dead wiki">{esc(text)}</a>')


def page_link(kind, id_, text, root):
    return f'<a class="xlink" href="{root}{kind}/{slug(id_, kind)}/">{esc(text)}</a>'


def traits(pairs):
    shown = [(label, value) for label, value in pairs if value]
    if not shown:
        return ''
    rows = ''.join(f'\n        <div class="trait"><dt>{esc(label)}</dt><dd>{value}</dd></div>'
                   for label, value in shown)
    return f'\n      <dl class="traits">{rows}\n      </dl>'


def section(title, body):
    if not body:
        return ''
    return (f'\n      <section class="detail-section">\n'
            f'        <h2 class="list-label">{esc(title)}</h2>\n'
            f'        {body}\n      </section>')


def buff_lines(description):
    return [line.strip() for line in (description or '').split('\n') if line.strip()]


def buff_line(line):
    at = line.rfind(':')
    if at < 1 or at == len(line) - 1:
        return f'<span class="stat">{esc(line)}</span>'
    return (f'<span class="stat">{esc(line[:at])}</span> '
            f'<span class="value">{esc(line[at + 1:].strip())}</span>')


def a_or_an(word):
    return f'{"an" if word[:1].lower() in "aeiou" else "a"} {word}'


def clip(text, limit=158):
    """
    A meta description: whole words, under the length a result shows,
    and a real dash -- the app's typewriter `--` reads as a typo in a
    search result.
    """
    text = ' '.join(text.replace(' -- ', ' – ').split())
    if len(text) <= limit:
        return text
    return text[:limit - 1].rsplit(' ', 1)[0].rstrip(',;:') + '…'


# ------------------------------------------------------------
# reading
# ------------------------------------------------------------

def load(db_path):
    con = sqlite3.connect(f'file:{db_path}?mode=ro', uri=True)
    con.row_factory = sqlite3.Row
    q = lambda sql: [dict(r) for r in con.execute(sql)]

    data = {
        'built_at': con.execute("SELECT value FROM meta WHERE key = 'built_at'").fetchone()[0],
        'ingredients': q('SELECT * FROM ingredients ORDER BY name'),
        'animals': defaultdict(list),
        'usage': defaultdict(list),
        'recipes': q('''
            SELECT r.*, st.name AS station, st.kind AS station_kind,
                   s.name AS set_name
            FROM   recipes r
            JOIN   stations st ON st.id = r.station_id
            LEFT JOIN sets s   ON s.id  = r.set_id
            ORDER  BY r.name'''),
        'ingredients_of': defaultdict(list),
    }
    for a in q('''
            SELECT ia.ingredient_id, a.name, a.link, a.bait, w.name AS weapon
            FROM   ingredient_animals ia
            JOIN   animals a ON a.id = ia.animal_id
            LEFT JOIN weapons w ON w.id = a.weapon_id
            ORDER  BY a.name'''):
        data['animals'][a['ingredient_id']].append(a)
    for u in q('''
            SELECT ri.ingredient_id, ri.qty, r.id AS recipe_id, r.name AS recipe,
                   r.repeatable, st.id AS station_id, st.name AS station,
                   loc.name AS location
            FROM   recipe_ingredients ri
            JOIN   recipes   r   ON r.id   = ri.recipe_id
            JOIN   stations  st  ON st.id  = r.station_id
            JOIN   locations loc ON loc.id = st.location_id
            ORDER  BY r.name'''):
        data['usage'][u['ingredient_id']].append(u)
    for i in q('''
            SELECT ri.recipe_id, ri.slot, ri.qty, ing.id AS ingredient_id,
                   ing.name, ing.quality
            FROM   recipe_ingredients ri
            JOIN   ingredients ing ON ing.id = ri.ingredient_id
            ORDER  BY ing.name'''):
        data['ingredients_of'][i['recipe_id']].append(i)
    con.close()
    return data


def slots(recipe, ingredients):
    """A recipe's ingredients as slots, as recipes.js groups them."""
    by_slot = defaultdict(list)
    for i in ingredients:
        by_slot[i['slot']].append(i)
    order = sorted(by_slot) if recipe['repeatable'] else list(by_slot)
    return [by_slot[s] for s in order]


# ------------------------------------------------------------
# the page around the content
# ------------------------------------------------------------

def shell_parts():
    """
    The CSP and the theme line, read out of index.html rather than
    written again here: the policy allows that script by its hash, so
    a copy that drifted by one byte would stop running.
    """
    index = (ROOT / 'index.html').read_text(encoding='utf-8')
    csp = re.search(r'<meta http-equiv="Content-Security-Policy"[^>]*>', index).group(0)
    theme = re.search(r'<script>\n(.*?)</script>', index, re.S).group(0)
    return csp, theme


def page(*, root, path, title, description, crumbs, tab, body, csp, theme, wide=False):
    url = SITE_URL + path
    crumb_ld = json.dumps({
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        'itemListElement': [
            {'@type': 'ListItem', 'position': n, 'name': name, 'item': SITE_URL + href}
            for n, (name, href) in enumerate(crumbs, 1)
        ],
    }, ensure_ascii=False)
    trail = ' <span aria-hidden="true">›</span> '.join(
        f'<a href="{root}{href}">{esc(name)}</a>' if n < len(crumbs) else
        f'<span aria-current="page">{esc(name)}</span>'
        for n, (name, href) in enumerate(crumbs, 1))
    here = ' class="here"'      # not inline: Python < 3.12 rejects a \" in an f-string
    tabs = '\n    '.join(
        f'<a href="{root}#/{route}"{here if route == tab else ""}>'
        f'<span class="icon icon-{ico}" aria-hidden="true"></span>{label}</a>'
        for route, label, ico in (('materials', 'Materials', 'materials'),
                                  ('recipes', 'Recipes', 'recipes'),
                                  ('inventory', 'Inventory', 'inventory'),
                                  ('settings', 'Settings', 'settings')))

    return f'''<!doctype html>
{MARKER}
<html lang="en">
<head>
<meta charset="utf-8">
{csp}
<meta name="referrer" content="no-referrer">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#e7dbc0">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{esc(url)}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="{SITE_NAME}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{esc(url)}">
<meta property="og:image" content="{SITE_URL}images/pixel-cowboy-campfire-at-dusk-960.jpg">
<link rel="icon" href="{root}images/favicon-32.png" sizes="32x32" type="image/png">
<link rel="apple-touch-icon" href="{root}images/apple-touch-icon.png">
<link rel="stylesheet" href="{root}app.css">
<script type="application/ld+json">{crumb_ld}</script>
{theme}
</head>
<body class="static">

<div class="chrome">
  <header class="topbar">
    <a class="brand" href="{root}">
      <img class="brand-mark" src="{root}images/logo-128.png" alt="" width="34" height="34">
      <span class="brand-text">
        <span class="brand-game">Red Dead Redemption II</span>
        <span class="brand-app">Crafting Guide</span>
      </span>
    </a>
  </header>
  <nav class="tabs">
    {tabs}
  </nav>
</div>

<div class="cover compact">
  <img src="{root}images/pixel-cowboy-campfire-at-dusk-960.jpg"
       srcset="{root}images/pixel-cowboy-campfire-at-dusk-960.jpg 960w, {root}images/pixel-cowboy-campfire-at-dusk-1920.jpg 1920w"
       sizes="100vw" alt="" width="1920" height="1080" decoding="async">
</div>

<main class="static-page{" static-wide" if wide else ""}">
  <nav class="crumbs" aria-label="Breadcrumb">{trail}</nav>
{body}
</main>

<footer class="footer">
  <p><span class="sym">&copy;</span> 2026 - Made with love by
     <span class="by">Arindam Bose</span>,
     powered by <span class="by">Claude</span></p>
  <p class="small-print">Browse <a href="{root}materials/">every material</a>
     or <a href="{root}recipes/">every recipe</a>.</p>
  <p class="small-print">Not affiliated with or endorsed by Rockstar Games
     or Take-Two Interactive</p>
</footer>
</body>
</html>
'''


def open_in_app(root, route, id_, what):
    return f'''
    <aside class="restore-offer static-cta">
      <p class="note"><strong>Track it in the guide.</strong> Log what you
        have and see what {what} still needs -- free, no sign-up, nothing
        leaves your device, and it works offline.</p>
      <a class="more-btn" href="{root}#/{route}/{esc(id_)}">Open in the crafting guide</a>
    </aside>'''


# ------------------------------------------------------------
# a material
# ------------------------------------------------------------

def material_page(m, data, parts):
    root = '../../'
    animals = data['animals'][m['id']]
    usage = data['usage'][m['id']]
    vendor_uses = [u for u in usage if not u['repeatable']]
    fire_uses = [u for u in usage if u['repeatable']]
    name = m['name']

    # What each vendor station asks for in all, every recipe counted --
    # the app's General mode.
    demand = defaultdict(int)
    for u in vendor_uses:
        demand[u['station_id']] += u['qty']
    stations = {u['station_id']: u for u in usage}
    vendors = [STATION_PROSE[s] for s in STATION_ORDER if s in demand]

    # The sentence a search result quotes.
    kind = 'crafting recipe' if vendor_uses else 'campfire recipe'
    said = [f'{name} is used in {plural(len(usage), kind)} in Red Dead Redemption 2']
    if vendors:
        said[0] += ' -- ' + listing(
            f'{plural(sum(1 for u in vendor_uses if u["station_id"] == s), "recipe")} '
            f'for {STATION_PROSE[s]}' for s in STATION_ORDER if s in demand)
        if fire_uses:
            said[0] += f', and {plural(len(fire_uses), "recipe")} at your campfire'
    said[0] += '.'
    if len(animals) == 1:
        a = animals[0]
        if a['bait']:
            said.append(f'It comes from the {a["name"]}; catch one with {a["bait"]}.')
        elif a['weapon']:
            said.append(f'It comes from the {a["name"]}; the {a["weapon"]} takes one '
                        f'cleanly, without spoiling the {(m["body_part"] or "carcass").lower()}.')
        else:
            said.append(f'It comes from the {a["name"]}.')
    elif animals:
        shown = [a['name'] for a in animals[:4]]
        more = f' and {len(animals) - 4} more' if len(animals) > 4 else ''
        said.append(f'It comes from {len(animals)} animals, including {", ".join(shown)}{more}.')
    intro = ' '.join(said)

    only = animals[0] if len(animals) == 1 else None
    if m['source_type'] == 'animal':
        facts = [('Animal', only and web_link(only['link'], only['name'])),
                 ('Quality', quality_label(m['quality'])),
                 ('Type', esc(m['body_part'])),
                 ('Weapon', only and esc(only['weapon'])),
                 ('Bait', only and esc(only['bait']))]
    elif m['source_type'] == 'misc':
        facts = [('Source', 'Found out in the world'), ('Quality', quality_label(m['quality']))]
    else:
        facts = []

    animal_list = len(animals) > 1 and (
        '<ul class="detail-list detail-animals">' + ''.join(
            f'\n          <li><span class="what">{web_link(a["link"], a["name"])}</span>'
            + (f'<span class="how">{esc("Bait: " + a["bait"] if a["bait"] else a["weapon"])}</span>'
               if a['bait'] or a['weapon'] else '') + '</li>'
            for a in animals) + '\n        </ul>')

    recipe_list = '<ul class="detail-list detail-recipes">' + ''.join(
        f'\n          <li class="plain"><span class="what">{u["qty"]}x for '
        f'{page_link("recipes", u["recipe_id"], u["recipe"], root)}'
        f'<small>{esc(u["station"])}</small></span></li>'
        for u in usage) + '\n        </ul>'

    stock = ''.join(
        f'\n          <div class="stock-line demand">'
        f'<span class="stock-text"><span class="station">{icon(STATION_ICON.get(s))}'
        f'{esc(stations[s]["station"])}</span> needs {demand[s]}'
        + (f'<small class="from">from your {esc(stations[s]["location"])}</small>'
           if stations[s]['location'] != stations[s]['station'] else '')
        + '</span></div>'
        for s in STATION_ORDER if s in demand)

    body = f'''
  <article class="static-detail">
    <header class="detail-head">
      <div>
        <p class="detail-kicker">{esc(KIND_LABEL.get(m["source_type"], "Material"))}</p>
        <h1>{esc(name)}{stars(m["quality"])}</h1>
      </div>
    </header>
    <p class="static-intro">{esc(intro)}</p>{traits(facts)}{section("Animals", animal_list)}{section("Recipes used in", recipe_list)}{section("Vendors", stock and f'<div class="detail-stock">{stock}</div>')}
  </article>{open_in_app(root, "materials", m["id"], "it")}'''

    where = listing(vendors + (['your campfire'] if fire_uses and vendors else []))
    description = clip(f'{name} in RDR2: used in {plural(len(usage), "recipe" if vendors else kind)}'
                       f'{" (" + where + ")" if where else ""}. '
                       + (said[1] + ' ' if len(said) > 1 else '')
                       + 'Every recipe it goes into, and how much each one needs.')
    return page(root=root, path=f'materials/{slug(m["id"], "materials")}/',
                title=f'{name}: RDR2 Uses & Recipes · {SITE_NAME}',
                description=description,
                crumbs=[('Crafting Guide', ''), ('Materials', 'materials/'),
                        (name, f'materials/{slug(m["id"], "materials")}/')],
                tab='materials', body=body, csp=parts[0], theme=parts[1])


# ------------------------------------------------------------
# a recipe
# ------------------------------------------------------------

def recipe_page(r, data, parts):
    root = '../../'
    ingredients = data['ingredients_of'][r['id']]
    groups = slots(r, ingredients)
    campfire = bool(r['repeatable'])
    buffs = buff_lines(r['description'])
    name = r['name']

    def slot_text(options):
        if len(options) == 1:
            return f'{options[0]["qty"]} {options[0]["name"]}'
        return f'{options[0]["qty"]} of any of ' + ' / '.join(o['name'] for o in options)

    def slot_line(options):
        if len(options) == 1:
            o = options[0]
            return (f'\n          <li><span class="qty">{o["qty"]}x</span>'
                    f'<span class="what">{page_link("materials", o["ingredient_id"], o["name"], root)}'
                    f'{stars(o["quality"])}</span></li>')
        names = ' / '.join(page_link('materials', o['ingredient_id'], o['name'], root) for o in options)
        return (f'\n          <li class="any"><span class="qty">{options[0]["qty"]}x</span>'
                f'<span class="what"><span class="any-of">any of</span> {names}</span></li>')

    needs = listing(slot_text(s) for s in groups)
    if campfire:
        intro = (f'{name} is a campfire recipe in Red Dead Redemption 2, made at your own '
                 f'campfire as often as you have the ingredients. It takes {needs}.')
        if r['price_cents']:
            intro += f' The recipe itself costs {money(r["price_cents"])}.'
    else:
        what = a_or_an((r['category'] or 'item').lower())
        intro = (f'{name} is {what} crafted by {STATION_PROSE[r["station_id"]]} '
                 f'in Red Dead Redemption 2. It takes {needs}')
        intro += f' and costs {money(r["price_cents"])}.' if r['price_cents'] else '.'
        if r['set_name']:
            intro += f' Part of {r["set_name"]}.'

    facts = ([('Type', esc(r['category'])),
              ('Made at', f'{icon("campfire")}{esc(r["station"])}'),
              ('Recipe cost', r['price_cents'] and money(r['price_cents']))]
             if campfire else
             [('Type', esc(r['category'])),
              ('Vendor', f'{icon(STATION_ICON.get(r["station_id"]))}{esc(r["station"])}'),
              ('Set', esc(r['set_name'])),
              ('Price', r['price_cents'] and money(r['price_cents']))])

    buff_list = buffs and ('<ul class="detail-list detail-buffs">' + ''.join(
        f'\n          <li>{buff_line(b)}</li>' for b in buffs) + '\n        </ul>')
    choice = len(ingredients) > len(groups)
    ingredient_list = ('<ul class="ingredients detail-ingredients">'
                       + ''.join(slot_line(s) for s in groups) + '\n        </ul>'
                       + ('\n        <p class="hint">"Any of" means all of one kind: the amount '
                          'cannot be made up from a mix.</p>' if choice else ''))

    body = f'''
  <article class="static-detail">
    <header class="detail-head">
      <div>
        <p class="detail-kicker">{"Campfire recipe" if campfire else "Recipe"}</p>
        <h1>{esc(name)}</h1>
      </div>
    </header>
    <p class="static-intro">{esc(intro)}</p>{traits(facts)}{section("Description", buff_list)}{section("Ingredients", ingredient_list)}
  </article>{open_in_app(root, "recipes", r["id"], "you")}'''

    first_buff = f' {buffs[0]}' if buffs else ''
    where = 'at your campfire' if campfire else f'by {STATION_PROSE[r["station_id"]]}'
    description = clip(f'{name} in RDR2: crafted {where} from {needs}.{first_buff}')
    kind_title = 'Campfire Recipe' if campfire else 'Recipe & Ingredients'
    return page(root=root, path=f'recipes/{slug(r["id"], "recipes")}/',
                title=f'{name}: RDR2 {kind_title} · {SITE_NAME}',
                description=description,
                crumbs=[('Crafting Guide', ''), ('Recipes', 'recipes/'),
                        (name, f'recipes/{slug(r["id"], "recipes")}/')],
                tab='recipes', body=body, csp=parts[0], theme=parts[1])


# ------------------------------------------------------------
# the A-Z lists
# ------------------------------------------------------------

def az_section(title, items, long_names=False):
    links = ''.join(f'\n        <li>{link}</li>' for link in items)
    kind = 'az-list long' if long_names else 'az-list'
    return (f'\n    <section class="detail-section">\n'
            f'      <h2 class="list-label">{esc(title)} <span class="count">{len(items)}</span></h2>\n'
            f'      <ul class="{kind}">{links}\n      </ul>\n    </section>')


def materials_index(data, parts):
    root = '../'
    body = ['''
  <article class="static-detail">
    <header class="detail-head"><div>
      <p class="detail-kicker">Red Dead Redemption 2</p>
      <h1>Every crafting material</h1>
    </div></header>
    <p class="static-intro">Every pelt, hide, plant and supply that goes into a
      crafting recipe in Red Dead Redemption 2, with what each one makes and
      where it comes from.</p>''']
    for title, kinds in GROUPS:
        items = [f'{page_link("materials", m["id"], m["name"], root)}{stars(m["quality"])}'
                 for m in data['ingredients'] if m['source_type'] in kinds]
        body.append(az_section(title, items))
    body.append('\n  </article>')
    return page(root=root, path='materials/',
                title=f'Every RDR2 Crafting Material, A-Z · {SITE_NAME}',
                description=clip(f'All {len(data["ingredients"])} crafting materials in Red Dead '
                                 'Redemption 2 -- pelts, hides, plants and supplies -- with the '
                                 'recipes each one goes into and where to find it.'),
                crumbs=[('Crafting Guide', ''), ('Materials', 'materials/')],
                tab='materials', body=''.join(body), csp=parts[0], theme=parts[1], wide=True)


def recipes_index(data, parts):
    root = '../'
    body = ['''
  <article class="static-detail">
    <header class="detail-head"><div>
      <p class="detail-kicker">Red Dead Redemption 2</p>
      <h1>Every crafting recipe</h1>
    </div></header>
    <p class="static-intro">Every recipe Pearson, the Trapper and the Fence
      craft in Red Dead Redemption 2, and every campfire recipe, with the
      ingredients each one takes.</p>''']
    station_names = {r['station_id']: r['station'] for r in data['recipes']}
    for s in STATION_ORDER:
        items = [page_link('recipes', r['id'], r['name'], root)
                 for r in data['recipes'] if r['station_id'] == s]
        if items:
            body.append(az_section(station_names[s], items, long_names=True))
    body.append('\n  </article>')
    return page(root=root, path='recipes/',
                title=f'Every RDR2 Crafting Recipe, A-Z · {SITE_NAME}',
                description=clip(f'All {len(data["recipes"])} crafting recipes in Red Dead '
                                 'Redemption 2 -- Pearson, the Trapper, the Fence and the '
                                 'campfire -- with the ingredients each one takes.'),
                crumbs=[('Crafting Guide', ''), ('Recipes', 'recipes/')],
                tab='recipes', body=''.join(body), csp=parts[0], theme=parts[1], wide=True)


def sitemap(paths, built_at):
    urls = ''.join(f'\n  <url><loc>{esc(SITE_URL + p)}</loc><lastmod>{built_at}</lastmod></url>'
                   for p in paths)
    return (f'<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">{urls}\n</urlset>\n')


# ------------------------------------------------------------
# writing
# ------------------------------------------------------------

def build(db_path):
    """Every file this makes, as {relative path: contents}."""
    data = load(db_path)
    parts = shell_parts()
    out = {
        'materials/index.html': materials_index(data, parts),
        'recipes/index.html': recipes_index(data, parts),
    }
    for m in data['ingredients']:
        out[f'materials/{slug(m["id"], "materials")}/index.html'] = material_page(m, data, parts)
    for r in data['recipes']:
        out[f'recipes/{slug(r["id"], "recipes")}/index.html'] = recipe_page(r, data, parts)

    pages = [''] + [p[:-len('index.html')] for p in out]
    out['sitemap.xml'] = sitemap(pages, data['built_at'])
    return out


def stale_folders(out):
    """Generated folders whose material or recipe is gone from the database."""
    keep = {Path(p).parent for p in out}
    for kind in PREFIX:
        for folder in sorted((ROOT / kind).glob('*/')):
            page_ = folder / 'index.html'
            if (folder.relative_to(ROOT) not in keep and page_.exists()
                    and MARKER in page_.read_text(encoding='utf-8')):
                yield folder


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('db', nargs='?', default=ROOT / 'data' / 'rdr2.db', type=Path)
    ap.add_argument('--check', action='store_true',
                    help='write nothing; exit 1 if any page is missing, stale or orphaned')
    args = ap.parse_args()

    out = build(args.db)
    changed = [p for p, text in out.items()
               if not (ROOT / p).exists() or (ROOT / p).read_text(encoding='utf-8') != text]
    orphans = list(stale_folders(out))

    if args.check:
        for p in changed:
            print(f'stale: {p}')
        for f in orphans:
            print(f'orphaned: {f.relative_to(ROOT)}/')
        print(f'{len(out)} files; {len(changed)} stale, {len(orphans)} orphaned')
        sys.exit(1 if changed or orphans else 0)

    for p in changed:
        (ROOT / p).parent.mkdir(parents=True, exist_ok=True)
        (ROOT / p).write_text(out[p], encoding='utf-8')
    for f in orphans:
        shutil.rmtree(f)
    print(f'{len(out)} files; wrote {len(changed)}, removed {len(orphans)} orphaned')


if __name__ == '__main__':
    main()
